//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLServerECommerce.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        public ShoppingCart()
        {
            this.ShoppingCart_Details = new HashSet<ShoppingCart_Details>();
        }
    
        public int id { get; set; }
        public string Description { get; set; }
        public Nullable<int> customer_id { get; set; }
        public Nullable<int> status { get; set; }
        public string Note { get; set; }
    
        public virtual ICollection<ShoppingCart_Details> ShoppingCart_Details { get; set; }
    }
}
