//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLServerECommerce.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public string meta_options { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> registration_date { get; set; }
        public Nullable<int> gender { get; set; }
        public Nullable<int> rating { get; set; }
        public string hash { get; set; }
        public string Email { get; set; }
    }
}
